### PR TITLE
Feature: Allow config file reset when config file is invalid (#24)

### PR DESCRIPTION
**Pull request by KSneijders**

### CODE REVIEW

**Comment by prelusion** [comment]
Looks good, only I get one Issue.


---> Bug?: App doesn't correctly restart after fixing the json.
---> Reproduce:
  1. Start app normally with correct json until you see the `create room` screen.
  2. Change json inside `userfolder/.xs-sync/config.json` to incorrect json.
  3. 'ctrl r' inside app to refresh application.
  4. (Bug happens).
  
---> What happens:
 1. Client force stops itself after restoring the json (So the app should shut down) but for some reason the electron app keeps running in a blank state which can't be interacted with.
 2. If you keep that blank client running you can't start the application. It  gives the following error: 
image
 3. After shutting down blank application and starting the app again from scratch it starts  working again like normal.

---> Expected? Either:
 1. Client force stops itself, the window also disappears and you can start it again from scratch without any error.
 2. (Better), the application restarts to the start screen without having to restart the application itself.

**Comment by prelusion** [comment]
For the rest it looks good

**Comment by KSneijders** [comment]
@prelusion 
> (Better), the application restarts to the start screen without having to restart the application itself.

I was thinking about this too, I thought it'd be easier to just restart the entire app. I'm not sure if this is a 'dev only' issue where the vite server stops because the app is shutdown and when it restarts it cannot connect to the vite server or something along those lines. 

It might be cleaner to just reset the `Loading` component. Thanks, I'll look into it!

**Comment by KSneijders** [comment]
@prelusion Just to confirm it was dev-only. When manually starting the vite server and reloading the restarted window using `ctrl + r` it would work, so in normal circumstances this would work. 
That being said, I've added a `reloadWindow` function to the store which resets the `Loading` progress and loads the settings from scratch.

**Comment by KSneijders** [comment]
I'll merge this PR now as this was the only blocking issue

**Pull request merged**
